[rewrite_local]
# 拦截instax API请求，替换响应内容
^https:\/\/instax\.app\.xcxd\.net\.cn\/api\/me url script-response-body url script-response-body https://raw.githubusercontent.com/51Hertz/QuantumultX/refs/heads/main/getINSTAXToken.js

[mitm]
hostname = instax.app.xcxd.net.cn
